### ISSUE TITLE
Reimplement GRValidation since it's conversion to swift 3

### ISSUE THREAD

**Issue by Dantali0n** [wayfindrltd/wayfindr-demo-ios#11]
Hello,

I have converted GRValidation to swift 3 which was previously used to validate graphs, edges etc..
I have submitted a pull request but you can find it here: https://github.com/Dantali0n/GRValidation

Since the development for GRValidation has sort of halted I would understand if you would not wish to re-implement GRValidation.

**Comment by axellundback** [comment]
@Dantali0n Thank you. GRValidation was only imported in one file and the method was actually unused so I removed it. If we need it in the future I would consider using [formvalidator-swift](https://github.com/ustwo/formvalidator-swift) which has similar functionality and is maintained by me and other developers here at ustwo.
