### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by axellundback** [wayfindrltd/wayfindr-demo-ios#9]
# Description

The dependencies in the read me file have been out dated since the migration to Swift 3

The updated dependencies should be:
 - Xcode 8.0
 - Cocoapods 1.1.1

**Comment by Dantali0n** [comment]
Hello, I am in the process of upgrading wayfindr-demo-ios to Swift 3 syntax and I'll be sure to update the readme as well before I submit a pull request.

**Update* 
I just saw you already did what I was doing, damn which I saw that earlier waisted a good 10+ hours... Oh well thats live~

**Comment by axellundback** [comment]
@Dantali0n Yeah I did the swift 3 migration 2 weeks ago, just missed the readme update. Sorry you spent all that time. Thank you so much for wanting to contribute to wayfindr tho.

**Comment by axellundback** [comment]
@Dantali0n If you have any improvements on your branch that I didn't have time to do you are more then welcome to add these. I deleted a few tests that weren't compatible with swift 3 and I didn't have time to go through the API and update it to a more Swift 3 like syntax.
